# Generated by Django 4.2.3 on 2023-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='service',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='service',
            name='organization_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='service',
            name='street_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='zip_code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'),
                                            ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'),
                                            ('brown', 'Brown'), ('gray', 'Gray')], default='gray', max_length=8),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(default='',
                                   help_text="Upload a 300x300 px to the 'static' directory. Add file path here",
                                   max_length=128),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='operation_hours',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
