# Generated by Django 4.2.3 on 2023-08-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_city_service_latitude_service_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='zip_code',
            new_name='address',
        ),
    ]
